
version: "3"

services:
  vue:
    build: ./frontend_timemanager
    ports:
      - "8080:80"
    depends_on:
      - phoenix
  phoenix:
    build: ./backend_timemanager
    volumes:
      - ./backend_timemanager:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "${PGDATA}"
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data