version: "3"

services:
  vue:
    build: ./frontend_timemanager
    image: timemanagerpar2.azurecr.io/vue
    ports:
      - "80:80"
    depends_on:
      - phoenix
  phoenix:
    build: ./backend_timemanager
    image: timemanagerpar2.azurecr.io/phoenix
    ports:
      - "4000:4000"
    environment:
      PGHOST: "db"
      PGPORT: 5432
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      PGDATABASE: "timemanager_dev"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always