on: [push]

name: AzureARMDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure-Docker
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          password: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}

      - name: Git Clone
        run:
          rm -rf my_code
          git clone https://github.com/segfault-master/epitech-timemanager.git my_code
          cd my_code
          docker-compose build

      - name: Docker Action
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az acr login --name timemanagerpar2
            docker-compose push
            docker context use mytimemanager
            docker compose up
            docker ps
